unfun_facts = [
    "Most dust in your home is made of dead skin cells.",
    "Honey never spoils, but it can contain botulism spores.",
    "A sneeze travels about 100 miles per hour, spreading germs everywhere.",
    "The average person spends about six months of their life waiting for red lights to turn green.",
    "Octopuses have three hearts, but two of them stop beating when they swim.",
    "The shortest war in history lasted 38 minutes, resulting in hundreds of deaths.",
    "Humans share 60% of their DNA with bananas.",
    "The longest time between two twins being born is 87 days, due to medical complications.",
    "Most people will outlive their teeth.",
    "The majority of your brain is fat.",
    "Most plastic ever made still exists somewhere on Earth.",
    "The world’s oceans contain more microplastics than stars in our galaxy.",
    "You are more likely to die on your birthday than any other day.",
    "The average mattress doubles in weight over 10 years due to dust mites and skin cells.",
    "Cockroaches can live for weeks without their heads.",
    "There are more vacant homes than homeless people in the world.",
    "Every year, millions of animals are killed on roads.",
    "Mosquitoes are responsible for more human deaths than any other animal.",
    "The inventor of the parachute died testing it.",
    "The inventor of the treadmill was executed.",
    "The inventor of the guillotine was executed by guillotine.",
    "More people die from falling coconuts than shark attacks.",
    "Your phone is dirtier than a toilet seat.",
    "The average person walks past 16 murderers in their lifetime.",
    "There are more fake flamingos in the world than real ones.",
    "You shed about 40 pounds of skin in your lifetime.",
    "The average desk has 400 times more bacteria than a toilet.",
    "Every minute, 20 people die worldwide.",
    "The human body starts to decompose four minutes after death.",
    "Your bones are constantly being replaced, but after age 30, you lose bone faster than you make it.",
    "The air you breathe contains millions of dead skin cells from other people.",
    "If the sun exploded, you wouldn't know for eight minutes.",
    "Most people have mites living on their eyelashes.",
    "A single teaspoon of soil contains more living organisms than people on Earth.",
    "The average person produces enough saliva in their lifetime to fill two swimming pools.",
    "Your stomach gets a new lining every few days to avoid digesting itself.",
    "The average person will spend about 2 years of their life in the bathroom.",
    "You are always breathing in tiny bits of insects and spider parts.",
    "Every year, you unknowingly eat about a pound of insects.",
    "The average pillow has thousands of dust mites living in it.",
    "Your shoes carry more bacteria than your toilet.",
    "The average person loses about 100 hairs a day.",
    "Most tap water contains traces of pharmaceuticals.",
    "The average person will spend 6 months of their life waiting in line.",
    "You are never more than 6 feet away from a spider.",
    "The average person will walk the equivalent of three times around the world in their lifetime.",
    "Your tongue print is unique, just like your fingerprints.",
    "The average person blinks 15-20 times per minute, about 28,800 times a day.",
    "Your heart beats about 100,000 times a day.",
    "You will produce about 25,000 quarts of saliva in your lifetime.",
    "The average person spends 1/3 of their life sleeping.",
    "Most people dream about 4-6 times per night, but forget 95% of their dreams.",
    "The average person will eat 35 tons of food in their lifetime.",
    "Your bones are stronger than steel, but can break easily.",
    "The average person has about 5 million hairs on their body.",
    "You lose about 1 million skin cells every day.",
    "The average person will spend 5 years of their life eating.",
    "Your body contains enough iron to make a small nail.",
    "The average person will spend 1 year of their life looking for lost items.",
    "You shed about 600,000 particles of skin every hour.",
    "The average person will spend 3 months of their life kissing.",
    "Your body replaces its entire skeleton every 10 years.",
    "The average person will spend 2 weeks of their life waiting for traffic lights.",
    "You are born with 300 bones, but adults have only 206.",
    "The average person will spend 1 year of their life cleaning.",
    "Your body contains enough carbon to fill 9,000 pencils.",
    "The average person will spend 6 months of their life sitting at red lights.",
    "You will produce about 50,000 liters of urine in your lifetime.",
    "The average person will spend 1 year of their life shopping.",
    "Your body contains enough sulfur to kill all fleas on a dog.",
    "The average person will spend 2 years of their life watching commercials.",
    "You will produce about 25,000 quarts of sweat in your lifetime.",
    "The average person will spend 1 year of their life exercising.",
    "Your body contains enough phosphorus to make 2,200 match heads.",
    "The average person will spend 2 years of their life working overtime.",
    "You will produce about 10,000 gallons of tears in your lifetime.",
    "The average person will spend 1 year of their life talking on the phone.",
    "Your body contains enough potassium to fire a toy cannon.",
    "The average person will spend 2 years of their life brushing their teeth.",
    "You will produce about 1,000 gallons of mucus in your lifetime.",
    "The average person will spend 1 year of their life laughing.",
    "Your body contains enough calcium to make a piece of chalk.",
    "The average person will spend 2 years of their life sneezing.",
    "You will produce about 1,000 gallons of earwax in your lifetime.",
    "The average person will spend 1 year of their life yawning.",
    "Your body contains enough magnesium to make a small firework.",
    "The average person will spend 2 years of their life scratching.",
    "You will produce about 1,000 gallons of tears in your lifetime.",
    "The average person will spend 1 year of their life hiccupping.",
    "Your body contains enough copper to make a penny.",
    "The average person will spend 2 years of their life coughing.",
    "You will produce about 1,000 gallons of saliva in your lifetime.",
    "The sun will eventually engulf the Earth in about 5 billion years.",
    "Most plastic ever created still exists in some form.",
    "Cockroaches can survive weeks without their heads.",
    "Sharks existed before trees.",
    "There are more abandoned houses than homeless people.",
    "Cigarette butts are the most littered item worldwide.",
    "Mosquitoes are responsible for more human deaths than any other animal.",
    "Lobsters used to be considered food for poor people and prisoners.",
    "Octopuses can feel pain and distress similar to mammals.",
    "Jellyfish have existed for over 500 million years with no brain.",
    "Every two minutes, we take more photos than the entire 19th century produced.",
    "Rats can laugh, but it sounds like ultrasonic squeaks we can't hear.",
    "More people die annually from vending machines than shark attacks.",
    "The Great Pacific Garbage Patch is twice the size of Texas.",
    "Antibiotic resistance is a growing global crisis.",
    "Bedbugs can survive for months without feeding.",
    "The average human swallows about eight spiders in their lifetime during sleep.",
    "Bananas are technically berries, but strawberries are not.",
    "Half the oxygen on Earth comes from ocean plankton that are dying due to climate change.",
    "Your body is home to more bacterial cells than human cells.",
    "The human brain starts to die within 5 minutes without oxygen.",
    "In 100 years, most modern buildings will collapse without maintenance.",
    "The average person spends 6 months of their life waiting at red lights."
]
